#!/usr/bin/env python
"""
FINAL THESIS ANALYSIS & VISUALIZATION SCRIPT

Purpose
-------
This script performs the FINAL analytical layer on the pair-level predictions
generated by the Phase-7 CNN256 inference pipeline.

It produces:
1. Uncertainty vs agreement visualization
2. Confident vs ambiguous performance summary
3. Error and ambiguity breakdown tables
4. CNN vs Random Forest benchmark comparison
5. Thesis-ready summary statistics

This script does NOT perform model inference.
It operates ONLY on the finalized pair-level CSV outputs.
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# INPUT / OUTPUT PATHS
# ============================================================

# Final pair-level predictions generated by inference script
FINAL_CSV = (
    "/vol/projects/znoor/cnn_training/3class_exp/"
    "FINAL_RESULTS/final_pair_predictions.csv"
)

# Random Forest baseline metrics (Phase-8)
# These are fixed reference values used for comparison
RF_SUMMARY = {
    "Macro F1": 0.7978918688803746,
    "MCC": 0.7203471383525607,
    "ROC-AUC": 0.9312339989759344
}

# Output directory for thesis figures and tables
OUT_DIR = (
    "/vol/projects/znoor/cnn_training/3class_exp/"
    "FINAL_RESULTS/THESIS_ASSETS"
)
os.makedirs(OUT_DIR, exist_ok=True)

# ============================================================
# LOAD FINAL PAIR-LEVEL RESULTS
# ============================================================

df = pd.read_csv(FINAL_CSV)

# Binary correctness indicator
df["correct"] = df["pred"] == df["true"]

# Human-readable confidence grouping
df["confidence_group"] = np.where(
    df["confident_prediction"], "Confident", "Ambiguous"
)

print("=" * 60)
print("FINAL PAIR-LEVEL ANALYSIS")
print("=" * 60)
print("Total pairs:", len(df))
print("Confident pairs:", (df["confidence_group"] == "Confident").sum())
print("Ambiguous pairs:", (df["confidence_group"] == "Ambiguous").sum())

# ============================================================
# 1. ENTROPY vs AGREEMENT SCATTER PLOT
# ============================================================
# This plot visualizes how prediction uncertainty (entropy)
# relates to segment-level consensus (agreement).
#
# Key interpretation:
# - Correct predictions cluster at high agreement + low entropy
# - Incorrect predictions are more dispersed
# - Justifies confidence thresholds used in inference

plt.figure(figsize=(6, 5))

# Incorrect predictions
plt.scatter(
    df.loc[~df["correct"], "agreement"],
    df.loc[~df["correct"], "entropy"],
    alpha=0.6,
    label="Incorrect"
)

# Correct predictions
plt.scatter(
    df.loc[df["correct"], "agreement"],
    df.loc[df["correct"], "entropy"],
    alpha=0.6,
    label="Correct"
)

plt.xlabel("Segment Agreement")
plt.ylabel("Entropy")
plt.title("Uncertainty vs Agreement (Pair Level)")
plt.legend()
plt.grid(alpha=0.3)

FIG1 = f"{OUT_DIR}/entropy_vs_agreement.png"
plt.savefig(FIG1, dpi=300, bbox_inches="tight")
plt.close()

print("Saved figure:", FIG1)

# ============================================================
# 2. CONFIDENT vs AMBIGUOUS PERFORMANCE SUMMARY
# ============================================================
# Aggregated statistics comparing confident vs ambiguous pairs.
# Used directly in Results tables.

summary_conf = (
    df.groupby("confidence_group")
      .agg(
          pairs=("pair_id", "count"),
          accuracy=("correct", "mean"),
          mean_entropy=("entropy", "mean"),
          mean_agreement=("agreement", "mean")
      )
      .reset_index()
)

CONF_TABLE = f"{OUT_DIR}/confidence_summary.csv"
summary_conf.to_csv(CONF_TABLE, index=False)

print("Saved table:", CONF_TABLE)

# ============================================================
# 3. ERROR / AMBIGUITY BREAKDOWN
# ============================================================
# Cross-tabulation of correctness within confidence groups.
# Shows how ambiguity correlates with misclassification.

error_table = (
    df.groupby(["confidence_group", "correct"])
      .size()
      .reset_index(name="count")
)

ERR_TABLE = f"{OUT_DIR}/error_breakdown.csv"
error_table.to_csv(ERR_TABLE, index=False)

print("Saved table:", ERR_TABLE)

# ============================================================
# 4. CNN vs RANDOM FOREST COMPARISON TABLE
# ============================================================
# Benchmark comparison between:
# - End-to-end CNN model (raw genomic segments)
# - Feature-engineered Random Forest baseline
#
# NOTE:
# CNN metrics here reflect FINAL calibrated Phase-7 performance.

comparison = pd.DataFrame([
    {
        "Model": "CNN256 (Phase-7)",
        "Macro F1": 0.82,
        "MCC": 0.74,
        "ROC-AUC": 0.91,
        "Input features": "Raw genomic segments"
    },
    {
        "Model": "Random Forest",
        "Macro F1": RF_SUMMARY["Macro F1"],
        "MCC": RF_SUMMARY["MCC"],
        "ROC-AUC": RF_SUMMARY["ROC-AUC"],
        "Input features": "Entropy, MI, #segments"
    }
])

COMP_TABLE = f"{OUT_DIR}/cnn_vs_rf_comparison.csv"
comparison.to_csv(COMP_TABLE, index=False)

print("Saved table:", COMP_TABLE)

# ============================================================
# 5. FINAL PRINTABLE SUMMARY (RESULTS SECTION)
# ============================================================
acc_all = df["correct"].mean()
acc_conf = df.loc[
    df["confidence_group"] == "Confident", "correct"
].mean()

print("\n===== FINAL SUMMARY =====")
print(f"Overall accuracy           : {acc_all:.3f}")
print(f"Accuracy (confident pairs) : {acc_conf:.3f}")
print("==========================")

print("\nFINAL THESIS ANALYSIS COMPLETE")
